apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=postgres;Port=5432;Database=fcg_payments_db;Username=payments;Password=paymentspw"
  RabbitMq__Password: guest
